jwt:
  secret: 'Z87f78dygVAFGV87AY78YV87vuaaf12by98g4q93q0wva0djv05Y4Q98VRUVH38YcvhYF9843Y9hfojeovhq'

  access:
    expiration: 20000
    header: Authorization

  refresh:
    expiration: 90
    header: Authorization-refresh